### PR TITLE
Add permission to be compatible with sylius rbac

### PR DESCRIPTION
**Pull request by hatem20**

### CODE REVIEW

**Comment by loevgaard** [comment]
Hi @hatem20 

What is it this PR does exactly? I am not much into the Sylius RBAC

**Comment by hatem20** [comment]
@loevgaard it adds the ability to add/remove `feed` to permissions 
As a super admin, I can control whether to allow some other admin to access feeds in the admin dashboard or not.

**Comment by loevgaard** [comment]
Okay. And I presume it doesn't affect anything else in Sylius?

Can you rebase your PR?

**Comment by hatem20** [comment]
I think it won't affect anything else, `permission` is only used by RBAC

**Comment by bigboss86** [comment]
Hi @loevgaard. Can you merge this PR?

**Pull request merged**
