### PR TITLE
Add support for league/flysystem 2

### PR DESCRIPTION
**Pull request by lruozzi9**
Differently from #69, these changes will support both v1 and v2 of league/flysystem.
@loevgaard what do you think? So that we can support Sylius 1.12 without any BC!

### CODE REVIEW

**Comment by loevgaard** [comment]
Great work, @lruozzi9!

Can you add this file: src/FeedContext/Google/Shopping/ProductItemContext.php to the ignored files in Psalm? I think that's the file that makes Psalm exhaust its memory limit. Then we should be able to make it build

**Comment by lruozzi9** [comment]
@loevgaard ok, but now there are a lot of errors already existing in master 😅. If you want I can try to fix the ones about this PR and add others to the baseline. Or add all to the baseline?

**Comment by loevgaard** [comment]
Haha, I see :D

The ones related to your change would be great to have fixed, so we don't add more errors. Thank you!

**Comment by lruozzi9** [comment]
@loevgaard I think now it is quite acceptable!

**Comment by lruozzi9** [comment]
@loevgaard Now here we are! I fixed an error due to the missing getMainRequest() method on Symfony 4.

**Comment by loevgaard** [comment]
Good morning, @lruozzi9.

I chose to make the `master` build so it might be easier for you with this PR.

Can you rebase onto `master`?

Thank you for all your work!

**Comment by loevgaard** [comment]
Thank you very much, @lruozzi9 🎉 

Great work!

**Pull request merged**
