### PR TITLE
Use variant specific image when possible

### PR DESCRIPTION
**Pull request by zambodaniel**
Currently, all variants has the same product image.
With this patch, it tries to find an image assigned to the current variant, if there is none, calls the original getImageLink() function.

### CODE REVIEW

**Comment by loevgaard** [comment]
Hi, @zambodaniel 

Can you rebase onto master? :)

**Comment by zambodaniel** [comment]
Hi, I've rebased.

**Comment by loevgaard** [comment]
Hi, @zambodaniel: I think you did a bit more than rebase. You have changed 69 files :)

**Comment by zambodaniel** [comment]
Hi, @loevgaard Please close this PR, I will make a clean one from another branch. I have made some commits not relevant to this in my master branch.

**Pull request closed without merging**
